name: Flutter Nightly Build (Win Only)

on:
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build-win.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
